<a href="https://colab.research.google.com/github/Avikg/Numpy_Pandas_Tutorials/blob/main/Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [6]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [10]:
b=np.ones((3,4), dtype=int)
print(b)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [26]:
c=np.random.random((3,4))
print(c)

[[0.63203872 0.13999347 0.30521837 0.76050992]
 [0.48499129 0.23500989 0.89093729 0.82915515]
 [0.57355189 0.62628204 0.04774964 0.32508572]]


In [28]:
d=np.linspace(-10, 20, 12, dtype=int)  #range:-10 to 20, no no nos generated:12(last one)
print(d.reshape(3,4))

[[-10  -8  -5  -2]
 [  0   3   6   9]
 [ 11  14  17  20]]


In [23]:
np.identity(3, dtype=int) #identity matrix of size 3X3

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

**Dimensionality**

In [44]:
a1=np.arange(10)
a2=np.arange(12, dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

print("a1", a1)
print("----------------------")
print("a2", a2)
print("----------------------")
print("a3", a3)

a1 [0 1 2 3 4 5 6 7 8 9]
----------------------
a2 [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
----------------------
a3 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [45]:
#ndim
print("a1-dim-", a1.ndim)
print("----------------------")
print("a2-dim-", a2.ndim)
print("----------------------")
print("a3-dim-", a3.ndim)

a1-dim- 1
----------------------
a2-dim- 2
----------------------
a3-dim- 3


In [46]:
#shape
print("a1-shape-", a1.shape)
print("----------------------")
print("a2-shape-", a2.shape)
print("----------------------")
print("a3-shape-", a3.shape)

a1-shape- (10,)
----------------------
a2-shape- (3, 4)
----------------------
a3-shape- (2, 2, 2)


In [52]:
#size
print("a1-size-", a1.size)
print("----------------------")
print("a2-size-", a2.size)
print("----------------------")
print("a3-size-", a3.size)

a1-size- 10
----------------------
a2-size- 12
----------------------
a3-size- 8


In [49]:
#itemsize    one nt/float how much memory allocated 'per item' (In colab int/float take same size i.e 1 Byte)
print("a1-itemsize-", a1.itemsize)
print("----------------------")
print("a2-itemsize-", a2.itemsize)
print("----------------------")
print("a3-itemsize-", a3.itemsize)


a1=np.arange(10, dtype=np.int32)
print("------------------------After Int 32-----------------------")
print("a1-itemsize-", a1.itemsize)
print("----------------------")
print("a2-itemsize-", a2.itemsize)
print("----------------------")
print("a3-itemsize-", a3.itemsize)


a1-itemsize- 4
----------------------
a2-itemsize- 8
----------------------
a3-itemsize- 8
------------------------After Int 32-----------------------
a1-itemsize- 4
----------------------
a2-itemsize- 8
----------------------
a3-itemsize- 8


In [50]:
#dtype
print("a1-dtype-", a1.dtype)
print("----------------------")
print("a2-dtype-", a2.dtype)
print("----------------------")
print("a3-dtype-", a3.dtype)

a1-dtype- int32
----------------------
a2-dtype- float64
----------------------
a3-dtype- int64


# **Changing Datatype**

In [61]:
print(a3.dtype)
a4=a3.astype(np.int32)
print("After changing-", a4.dtype)
a4

int64
After changing- int32


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

**Array Operations**

In [65]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

print('a1-', a1)
print('-----------------')
print('a2-', a2)

a1- [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-----------------
a2- [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


Scalar Operations

In [78]:
#arithmetic
print(a1)
print('-----------------')



print('a1*2-', a1*2)
print('-----------------')
print('a1+2-', a1+2)
print('-----------------')
print('a1-2-', a1-2)
print('-----------------')
print('a1/2-', a1/2)
print('-----------------')
print('a1%2-', a1%2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-----------------
a1*2- [[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
-----------------
a1+2- [[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
-----------------
a1-2- [[-2 -1  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]]
-----------------
a1/2- [[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]
-----------------
a1%2- [[0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]]


In [77]:
#relational
print(a2)
print('-----------------')


print('a2>5-', a2>5)
print('-----------------')
print('a2>25-', a2>25)
print('-----------------')
print('a2>15-', a2>15)
print('-----------------')
print('a2==15-', a2==15)
print('-----------------')
print('a2!=15-', a2!=15)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
-----------------
a2>5- [[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
-----------------
a2>25- [[False False False False]
 [False False False False]
 [False False False False]]
-----------------
a2>15- [[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]
-----------------
a2==15- [[False False False  True]
 [False False False False]
 [False False False False]]
-----------------
a2!=15- [[ True  True  True False]
 [ True  True  True  True]
 [ True  True  True  True]]


Vector Operations

In [81]:
#arithmetic

print('a1+a2-\n', a1+a2)
print('-----------------')
print('a1*a2-\n', a1*a2)

a1+a2-
 [[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
-----------------
a1*a2-
 [[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]


In [87]:
#dot product    a.b^T
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a.shape)
print(b.shape)
print(np.dot(a,b))
print(a@b)   ## Can be used for Matrix Multiplication also

(3,)
(3,)
32
32
