<a href="https://colab.research.google.com/github/Avikg/Numpy_Pandas_Tutorials/blob/main/Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
b=np.ones((3,4), dtype=int)
print(b)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [ ]:
c=np.random.random((3,4))
print(c)

[[0.63203872 0.13999347 0.30521837 0.76050992]
 [0.48499129 0.23500989 0.89093729 0.82915515]
 [0.57355189 0.62628204 0.04774964 0.32508572]]


In [ ]:
d=np.linspace(-10, 20, 12, dtype=int)  #range:-10 to 20, no no nos generated:12(last one)
print(d.reshape(3,4))

[[-10  -8  -5  -2]
 [  0   3   6   9]
 [ 11  14  17  20]]


In [ ]:
np.identity(3, dtype=int) #identity matrix of size 3X3

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

**Dimensionality**

In [ ]:
a1=np.arange(10)
a2=np.arange(12, dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

print("a1", a1)
print("----------------------")
print("a2", a2)
print("----------------------")
print("a3", a3)

a1 [0 1 2 3 4 5 6 7 8 9]
----------------------
a2 [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
----------------------
a3 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
#ndim
print("a1-dim-", a1.ndim)
print("----------------------")
print("a2-dim-", a2.ndim)
print("----------------------")
print("a3-dim-", a3.ndim)

a1-dim- 1
----------------------
a2-dim- 2
----------------------
a3-dim- 3


In [ ]:
#shape
print("a1-shape-", a1.shape)
print("----------------------")
print("a2-shape-", a2.shape)
print("----------------------")
print("a3-shape-", a3.shape)

a1-shape- (10,)
----------------------
a2-shape- (3, 4)
----------------------
a3-shape- (2, 2, 2)


In [ ]:
#size
print("a1-size-", a1.size)
print("----------------------")
print("a2-size-", a2.size)
print("----------------------")
print("a3-size-", a3.size)

a1-size- 10
----------------------
a2-size- 12
----------------------
a3-size- 8


In [ ]:
#itemsize    one nt/float how much memory allocated 'per item' (In colab int/float take same size i.e 1 Byte)
print("a1-itemsize-", a1.itemsize)
print("----------------------")
print("a2-itemsize-", a2.itemsize)
print("----------------------")
print("a3-itemsize-", a3.itemsize)


a1=np.arange(10, dtype=np.int32)
print("------------------------After Int 32-----------------------")
print("a1-itemsize-", a1.itemsize)
print("----------------------")
print("a2-itemsize-", a2.itemsize)
print("----------------------")
print("a3-itemsize-", a3.itemsize)


a1-itemsize- 4
----------------------
a2-itemsize- 8
----------------------
a3-itemsize- 8
------------------------After Int 32-----------------------
a1-itemsize- 4
----------------------
a2-itemsize- 8
----------------------
a3-itemsize- 8


In [ ]:
#dtype
print("a1-dtype-", a1.dtype)
print("----------------------")
print("a2-dtype-", a2.dtype)
print("----------------------")
print("a3-dtype-", a3.dtype)

a1-dtype- int32
----------------------
a2-dtype- float64
----------------------
a3-dtype- int64


# **Changing Datatype**

In [ ]:
print(a3.dtype)
a4=a3.astype(np.int32)
print("After changing-", a4.dtype)
a4

int64
After changing- int32


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

**Array Operations**

In [ ]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

print('a1-', a1)
print('-----------------')
print('a2-', a2)

a1- [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-----------------
a2- [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


Scalar Operations

In [ ]:
#arithmetic
print(a1)
print('-----------------')



print('a1*2-', a1*2)
print('-----------------')
print('a1+2-', a1+2)
print('-----------------')
print('a1-2-', a1-2)
print('-----------------')
print('a1/2-', a1/2)
print('-----------------')
print('a1%2-', a1%2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-----------------
a1*2- [[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
-----------------
a1+2- [[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
-----------------
a1-2- [[-2 -1  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]]
-----------------
a1/2- [[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]
-----------------
a1%2- [[0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]]


In [ ]:
#relational
print(a2)
print('-----------------')


print('a2>5-', a2>5)
print('-----------------')
print('a2>25-', a2>25)
print('-----------------')
print('a2>15-', a2>15)
print('-----------------')
print('a2==15-', a2==15)
print('-----------------')
print('a2!=15-', a2!=15)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
-----------------
a2>5- [[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
-----------------
a2>25- [[False False False False]
 [False False False False]
 [False False False False]]
-----------------
a2>15- [[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]
-----------------
a2==15- [[False False False  True]
 [False False False False]
 [False False False False]]
-----------------
a2!=15- [[ True  True  True False]
 [ True  True  True  True]
 [ True  True  True  True]]


Vector Operations

In [113]:
#arithmetic

print('a1+a2-\n', a1+a2)
print('-----------------')
print('a1*a2-\n', a1*a2)

a1+a2-
 [[ 27  35  60  61]
 [ 52  49  30  82]
 [ 26  44 101  58]]
-----------------
a1*a2-
 [[ 180  286  644  690]
 [ 576  544  216 1197]
 [ 120  483 1738  805]]


**Array Functions**

In [ ]:
a1=np.random.random((3,4))
print('a1-\n', a1)
a1=np.round(a1*100).astype(np.int64)
print('After operation, a1-\n', a1)

a1-
 [[0.15441702 0.22240596 0.46493978 0.46028132]
 [0.35528569 0.32373343 0.11709479 0.62831898]
 [0.06256456 0.22545649 0.79197208 0.34839992]]
After operation, a1-
 [[15 22 46 46]
 [36 32 12 63]
 [ 6 23 79 35]]


In [ ]:
#max/min/sum/product
print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))

79
6
415
232048144394035200


In [ ]:
#max/min/sum/product for every row
#axis---->  0 means column and 1 means row
print(np.max(a1, axis=1))
print(np.min(a1, axis=1))
print(np.sum(a1, axis=1))
print(np.prod(a1, axis=1))

[46 63 79]
[15 12  6]
[129 143 143]
[698280 870912 381570]


In [ ]:
#mean/median/std/var
print(np.mean(a1, axis=1))
print(np.median(a1, axis=1))
print(np.std(a1, axis=1))
print(np.var(a1, axis=1))

[32.25 35.75 35.75]
[34. 34. 29.]
[13.97095201 18.17106216 27.01272848]
[195.1875 330.1875 729.6875]


In [ ]:
#trigonometric functions
print(np.sin(a1))

[[ 0.65028784 -0.00885131  0.90178835  0.90178835]
 [-0.99177885  0.55142668 -0.53657292  0.1673557 ]
 [-0.2794155  -0.8462204  -0.44411267 -0.42818267]]


In [120]:
#dot product    a.b^T
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a.shape)
print(b.shape)
print('a\n', a)
print('b\n', b)
print(np.dot(a,b))
print(a@b)   ## Can be used for Matrix Multiplication also

print('--------------')
a1=np.arange(12).reshape(3,4)
a2=np.arange(12, 24).reshape(4,3)
print('a1\n', a1)
print('a2\n', a2)
print('Dot Product\n', np.dot(a1, a2))
print('Dot Product\n', a1@a2)

(3,)
(3,)
a
 [1 2 3]
b
 [4 5 6]
32
32
--------------
a1
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
a2
 [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
Dot Product
 [[114 120 126]
 [378 400 422]
 [642 680 718]]
Dot Product
 [[114 120 126]
 [378 400 422]
 [642 680 718]]


In [123]:
#log and exponents
print('a1_log\n', np.log(a1))
print('a1_exp\n', np.exp(a1))

a1_log
 [[      -inf 0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947 1.94591015]
 [2.07944154 2.19722458 2.30258509 2.39789527]]
a1_exp
 [[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03]
 [2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04]]


<ipython-input-123-06b1e1c263f0>:2: RuntimeWarning: divide by zero encountered in log
  print('a1_log\n', np.log(a1))


In [134]:
#round/floor/ceil
print(np.random.random((2,3)))
print('-----------------------------')
print(np.random.random((2,3))*100)
print('-----------------------------')
print(np.round(np.random.random((2,3))*100))
print('-----------------------------')
print(np.floor(np.random.random((2,3))*100))
print('-----------------------------')
print(np.ceil(np.random.random((2,3))*100))
print('-----------------------------')
print(np.ceil(np.random.random((2,3))*100).astype(dtype=np.int64))

[[0.29678476 0.72420915 0.82632064]
 [0.22789777 0.81008756 0.2252939 ]]
-----------------------------
[[19.72121467 62.04317399 87.61575895]
 [79.54864135 80.98841477 40.90897783]]
-----------------------------
[[84. 53. 95.]
 [87. 93. 12.]]
-----------------------------
[[77. 41. 83.]
 [56.  5. 61.]]
-----------------------------
[[62.  3. 83.]
 [99. 39. 61.]]
-----------------------------
[[39 43 38]
 [70 38 29]]


**Indexing and Slicing**

In [141]:
a1=np.arange(10)
print('a1\n', a1)
a2=np.arange(12).reshape(3,4)
print('a2\n', a2)
a3=np.arange(8).reshape(2,2,2)
print('a3\n', a3)

a1
 [0 1 2 3 4 5 6 7 8 9]
a2
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
a3
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [150]:
#lastitem/firstitem of a1
print('last item of a1-', a1[-1])
print('first item of a1-', a1[0])


#2d array
#I want 6
print(a2[1, 2])

##I want 4
print(a2[1, 0])



#3d array
#I want 5
print(a3[1, 0, 1])

#I want 2
print(a3[0, 1, 0])

#I want 0
print(a3[0, 0, 0])


last item of a1- 9
first item of a1- 0
6
4
5
2
0


In [192]:
#slicing
print(a1)

#2,3,4
print(a1[2:5])
print(a1[2:5:2])

print('-----------')

#for 2d
print(a2)
#for first row
print(a2[0, :])
#for third column
print(a2[:, 2])
# for 5,6, 9,10
print(a2[1:, 1:3])
# for 0,3,8,11
print(a2[::2, ::3])
# for 1,3,9,11
print(a2[::2, 1::2])
# for 4,7
print(a2[1, ::3])

print('-----------')

#for 3d
a3=np.arange(27).reshape(3,3,3)   #contains 3 nos of 2-d arrays of size(3,3)
print(a3)
print('-------Operations------')
#for middle 2d array
print(a3[1, :, :])
#for middle 1st and last array
print(a3[::2, :, :])  #or print(a3[::2])
#1st one 2d array ka 2nd row
print(a3[0, 1]) #or print(a3[0, 1, :])
#2nd one 2d array ka middle column
print(a3[1, ::, 1]) #or print(a3[1,:, 1])
#for 22, 23, 25,26
print(a3[2, 1:, 1:])
#for 0,2,18,20
print(a3[::2, 0, ::2])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]
[2 4]
-----------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]
[ 2  6 10]
[[ 5  6]
 [ 9 10]]
[[ 0  3]
 [ 8 11]]
[[ 1  3]
 [ 9 11]]
[4 7]
-----------
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
-------Operations------
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[3 4 5]
[10 13 16]
[[22 23]
 [25 26]]
[[ 0  2]
 [18 20]]


**Iterating**

In [193]:
print('a1\n', a1)
print('a2\n', a2)
print('a3\n', a3)

a1
 [0 1 2 3 4 5 6 7 8 9]
a2
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
a3
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [203]:
#for 1d
for i in a1:
  print(i, end=" ")

print('\n------------')

#for 2d
for i in a2:
  print(i)

print('------------')

#for 3d
for i in a3:
  print(i)

print('------------')

#for each item for 1d, 2d and 3d
for i in np.nditer(a3):
  print(i, end=" ")


0 1 2 3 4 5 6 7 8 9 
------------
[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
------------
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]
------------
0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 

**Reshaping**

In [204]:
#reshape ---already done

In [207]:
#transpose
print(a2)
print("After Transpose\n", np.transpose(a2))
#or
print(a2.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
After Transpose
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [214]:
#ravel    any dimension array to 1d
print(a2)
print(a2.ravel())
print(a3.ravel())

for i in a3.ravel():
  print(i, end=" ")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]
0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 

**Stacking**

In [222]:
#horizontal stacking---------2X2 and 2X2 two arrays(any no arrays possible), after op, 2X4
a4=np.arange(12).reshape(3,4)
a5=np.arange(12, 24).reshape(3,4)
print(a4)
print(a5)
print('------Afetr Operation------')
print(np.hstack((a4,a5,a4,a5)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
------Afetr Operation------
[[ 0  1  2  3 12 13 14 15  0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19  4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23  8  9 10 11 20 21 22 23]]


In [223]:
#vertical stacking----------2X2 and 2X2 two arrays(any no arrays possible), after op, 4X2
print(np.vstack((a4,a5,a4,a5)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


**Splitting**
splitting opposite of stacking

In [232]:
#horizontal splitting
print(a4)
print(np.hsplit(a4, 2))  # cut into 2 parts
print(np.hsplit(a4, 4))  # cut into 4 parts

for i in np.hsplit(a4, 4):
  print(i)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[0],
       [4],
       [8]]), array([[1],
       [5],
       [9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]
[[0]
 [4]
 [8]]
[[1]
 [5]
 [9]]
[[ 2]
 [ 6]
 [10]]
[[ 3]
 [ 7]
 [11]]


In [235]:
#vertical splitting
print(a5)
print(np.vsplit(a5, 3))  # cut into 3 parts
#print(np.vsplit(a5, 4))  # cut into 4 parts

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[array([[12, 13, 14, 15]]), array([[16, 17, 18, 19]]), array([[20, 21, 22, 23]])]
